# Generated by Django 5.0.1 on 2024-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='https://github.com/mitruho'),
            preserve_default=False,
        ),
    ]
