# Generated by Django 5.0.1 on 2024-09-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='website',
        ),
    ]
