# Generated by Django 5.0.1 on 2024-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_url_project_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gif',
            field=models.ImageField(default='portfolio/default.png', upload_to='portfolio/gifs/'),
        ),
    ]
